import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-[100dvh] outline-1">
        <NavBar />
        <div className="outline-1 p-6 pt-28 flex flex-col gap-6 self-center md:pt-46 md:w-277">
          {children}
        </div>
      </body>
    </html>
  );
}

// md:w-277 md:px-0 md:justify-center